language: cpp
sudo: false

addons:
  coverity_scan:
    project:
      name: "nayan-dev/ardupilot"
      description: "Build submitted via Travis CI"
    notification_email: siddharth@aus.co.in
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
    
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
      - build-essential
      - gawk
      - ccache
      - genromfs
      - libc6-i386
      - libxml2-dev
      - libxslt1-dev
      - python-pip
      - python-dev
      - zlib1g-dev
      - gcc-4.9
      - g++-4.9
      - cmake
      - cmake-data
#      - clang-3.7
#      - llvm-3.7

cache:
  ccache: true
  directories:
    - $HOME/opt

before_install:
  - Tools/scripts/configure-ci.sh
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then export CI_CRON_JOB=1 ; fi

script:
- python Tools/autotest/param_metadata/param_parse.py
- Tools/scripts/build_ci.sh
before_cache:
  - ccache -z

notifications:
  slack: aus-india:8ODz7BnNXaDZei1VcvvbyDdT
compiler:
- gcc
env:
  global:
  - secure: FjIwqZQV2FhNPWYITX5LZXTE38yYqBaQdbm3QmbEg/30wnPTm1ZOLIU7o/aSvX615ImR8kHoryvFPDQDWc6wWfqTEs3Ytq2kIvcIJS2Y5l/0PFfpWJoH5gRd6hDThnoi+1oVMLvj1+bhn4yFlCCQ2vT/jxoGfiQqqgvHtv4fLzI=
matrix:
  fast_finish: true
  include:
  - compiler: gcc
    env: CI_BUILD_TARGET="sparrow-v10 sparrow-v11"
  - compiler: gcc
    env: CI_BUILD_TARGET="sitltest"
deploy:
  provider: releases
  api_key:
    secure: cAZVgiEI9tBwFW98Zvz/bW47XiI8K39Mzv9Xx6ChGRJLBrwUdSM34tSlLu50Rw4m34FeddaQDeNlncOtoR3+vjvk4NPIQw6ktUGQxMN4gbM8wO/td7yt2zDvekRsG7F1LAps9DfvKGtC1Ylba4oDlll/UX44L4C6HnbBnxulQNVEe7xsoHntG7qSN7rB6mDC4LjSPtrYl+vHNwhIaSIdDZ2e1VuPl4pbmBmUGgRi1rf6LnQH67gh7PB9sGVWqcWRvIzpAfODMbn2aHn/1hvc1R+Begv6qBK/87nUQoMDe8hd8E6aWagptNrXw1IlK2ZbOYajHbUjGH4FEcQ/wIXsLf0TR1DIMtoigOKRd0imZq2Ts4bc6POoMkx14jVBY7rra0gZgghMmKJRjAUyvYI2tACn+6dAdM5FL7qK+VGE2apZ4DUx+lwmHvypO4WyUbiyl5sF7gpgr2aM+QCjz77V0qTJ2HQuwnpHnyEoSSgyqvX5ty2fLa5/Rae7w3YxcVV8xiWTb5ulc+17ftxNf3WqFca6y69CUqKeIl8/f+P2TN8GaifxwKTf+26N6HT0EVh7CZSo1cXT23jFqUm8wjk4y8YEhD4irR9ySOuJVFRbf8/7B82pcaFB3bwI8mMlrOvN8Ou/zCxJJn6HceRLi2Ld0NXTTd9GQNw7KZwgalvh2bM=
  file: ArduPlane/ArduPlane-sparrow-v10.px4
  on:
    repo: nayan-dev/ardupilot
    tags: true
